---
version: '3'

services:
  apt-cacher-ng:
    image: sameersbn/apt-cacher-ng
    container_name: wld-apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - wld-apt-cacher-ng:/var/cache/apt-cacher-ng
    restart: always

volumes:
  wld-apt-cacher-ng:
